import { DefaultTheme } from 'styled-components/macro';

export const defaultTheme: DefaultTheme = {
   name: 'defaultTheme',
   colors: {
      background: '#a4a9d2',
      main: '#ffc0cb',
      text: '#000000',
      headerButtonOne: '#f06daa',
      headerButtonTwo: '#e188b2',
      headerButtonThree: '#f5a1c8',
      translationBoxOne: '#ffc0cb4c',
      translationBoxTwo: '#e7a3bf6f',
      searchIcon: '#000000',
      searchSelection: '#ffc0cb',
      collapseSearchSelection: '#ffffff',
      gridLines: '#ffffff',
      cardBackground: '#ffffff',
      breakline: '#93939317',
   },
};

export const blueTheme: DefaultTheme = {
   name: 'blueTheme',
   colors: {
      background: '#8dd0f0',
      main: '#74d1fc',
      text: '#000000',
      headerButtonOne: '#1cadf0',
      headerButtonTwo: '#39b2ea',
      headerButtonThree: '#5abce9',
      translationBoxOne: '#86d0f1',
      translationBoxTwo: '#59b9e6',
      gameIcon: '#c6d57e',
      searchIcon: '#000000',
      searchSelection: '#77b6db',
      collapseSearchSelection: '#ffffff',
      gridLines: '#d3f1fe',
      cardBackground: '#c9eeff',
      breakline: '#a4adb214',
   },
};

export const darkTheme: DefaultTheme = {
   name: 'darkTheme',
   colors: {
      background: '#222831',
      main: '#393e46',
      text: '#eeeeee',
      headerButtonOne: '#1d1e1f',
      headerButtonTwo: '#555758',
      headerButtonThree: '#7d7f81',
      translationBoxOne: '#8f959f',
      translationBoxTwo: '#464f5a',
      voltageIcon: '#76c9db',
      starIcon: '#a3db76',
      gameIcon: '#bd70d9',
      gameScreenIcon: '#d5b5e0',
      alienIcon: '#e1d26d',
      rainbowIconFillOne: '#bd70d9',
      rainbowIconFillTwo: '#76c9db',
      rainbowIconFillThree: '#a3db76',
      rainbowIconFillFour: '#e1d26d',
      rainbowIconFillFive: '#dbc376',
      rainbowIconFillSix: '#8b8b8b',
      chevronIcon: '#eeeeee',
      searchIcon: '#eeeeee',
      searchSelection: '#393e46',
      collapseSearchSelection: '#eeeeee',
      gridLines: '#616161',
      cardBackground: '#6c7480',
      breakline: '#a7a7a717',
   },
};

export const greenTheme: DefaultTheme = {
   name: 'greenTheme',
   colors: {
      background: '#9fd8af',
      main: '#539165',
      text: '#000000',
      headerButtonOne: '#0c5149',
      headerButtonTwo: '#4fb37c',
      headerButtonThree: '#a5c3a7',
      translationBoxOne: '#e1f2e2',
      translationBoxTwo: '#51a17a',
      gameIcon: '#7dbfe0',
      alienIcon: '#ce8def',
      rainbowIconFillOne: '#ef8257',
      rainbowIconFillTwo: '#4491be',
      rainbowIconFillThree: '#a04ac5',
      rainbowIconFillFour: '#50be44',
      rainbowIconFillFive: '#db4343',
      rainbowIconFillSix: '#e4cd1c',
      searchIcon: '#000000',
      searchSelection: '#539165',
      collapseSearchSelection: '#ffffff',
      gridLines: '#c4f4cd',
      cardBackground: '#c7e8ca',
      breakline: '#e4fadc2a',
   },
};

export const rainbowTheme: DefaultTheme = {
   name: 'rainbowTheme',
   colors: {
      background:
         'radial-gradient( circle farthest-corner at 10% 20%,  rgba(222,168,248,1) 0%, rgba(168,222,248,1) 21.8%, rgba(189,250,205,1) 35.6%, rgba(243,250,189,1) 52.9%, rgba(250,227,189,1) 66.8%, rgba(248,172,172,1) 90%, rgba(254,211,252,1) 99.7% )',
      main: 'linear-gradient( 109.6deg,  rgba(255,179,189,1) 1.8%, rgba(254,248,154,1) 50.6%, rgba(161,224,186,1) 100.3% )',
      text: '#000000',
      headerButtonOne: '#65d08e',
      headerButtonTwo: '#63bbe1',
      headerButtonThree: '#e98eed',
      translationBoxOne: '#d7bcc8',
      translationBoxTwo: '#FFF9CA',
      voltageIcon: '#90f1ef',
      starIcon: '#7bf1a8',
      gameIcon: '#63bbe1',
      gameScreenIcon: '#ededed',
      alienIcon: '#c1fba4',
      rainbowIconFillOne: '#90f1ef',
      rainbowIconFillTwo: '#ffd6e0',
      rainbowIconFillThree: '#ffef9f',
      rainbowIconFillFour: '#c1fba4',
      rainbowIconFillFive: '#7bf1a8',
      rainbowIconFillSix: '#e98eed',
      chevronIcon: '#000000',
      searchIcon: '#000000',
      searchSelection: '#000000',
      collapseSearchSelection: '#ffffff',
      gridLines: '#ffffff',
      cardBackground: '#fac8cd',
      breakline: '#f6fadc34',
      dropdownOption: '#b0e4b5',
      dropdownText: '#ffffff',
      servicesDropdown: '#fdeca1',
   },
};

export const purpleTheme: DefaultTheme = {
   name: 'purpleTheme',
   colors: {
      background: '#635985',
      main: '#443c68',
      text: '#f7f1e5',
      headerButtonOne: '#7055a6',
      headerButtonTwo: '#8e6ad5',
      headerButtonThree: '#ab88f0',
      translationBoxOne: '#c8b2df',
      translationBoxTwo: '#a881cf',
      gameIcon: '#a72f2f',
      alienIcon: '#74d1fc',
      rainbowIconFillOne: '#b399c8',
      rainbowIconFillTwo: '#92d3f5',
      rainbowIconFillThree: '#b1cc33',
      rainbowIconFillFour: '#fcea2b',
      rainbowIconFillFive: '#f4aa41',
      rainbowIconFillSix: '#ea5a47',
      chevronIcon: '#f7f1e5',
      searchIcon: '#f7f1e5',
      searchSelection: '#443c68',
      collapseSearchSelection: '#ffffff',
      gridLines: '#c1afe7d9',
      cardBackground: '#b8a0d0',
      breakline: '#fadcdc0d',
   },
};

export const yellowTheme: DefaultTheme = {
   name: 'yellowTheme',
   colors: {
      background: '#ffe5a2',
      main: '#ffd98e',
      text: '#000000',
      headerButtonOne: '#89A4c7',
      headerButtonTwo: '#d8aed3',
      headerButtonThree: '#ffa5a5',
      translationBoxOne: '#f8f1ca',
      translationBoxTwo: '#fee9b2',
      voltageIcon: '#deecfc',
      starIcon: '#d6f8b8',
      gameIcon: '#99ddcfc',
      alienIcon: '#e6A4b4',
      rainbowIconFillOne: '#ffc1b6',
      rainbowIconFillTwo: '#c1ffd7',
      rainbowIconFillThree: '#b5deff',
      rainbowIconFillFour: '#cab8ff',
      rainbowIconFillFive: '#eec4c4',
      rainbowIconFillSix: '#fdffbc',
      searchIcon: '#000000',
      searchSelection: '#ffd98e',
      collapseSearchSelection: '#ffffff',
      gridLines: '#f3cb94',
      cardBackground: '#fffeec',
      breakline: '#c3bcb014',
   },
};
